using System.Numerics;
using Content.Client.UserInterface.Screens;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.RTS.UI;

/// <summary>
/// Полноэкранный интерфейс RTS. Базовый HUD станции сюда не попадает вообще:
/// нет ни хотбара, ни инвентаря, ни рук, ни алертов, ни верхнего меню.
///
/// Чат оставлен намеренно — игрокам и админам нужен канал связи, и без виджета
/// ChatBox падает ChatUIController.SetMainChat.
/// См. Docs/ADT/RTS/RTS_MASTER_PLAN.md §5.1.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RtsGameScreen : InGameScreen
{
    public RtsGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        // Нужно ровно для колеса: MouseWheel вызывается только у контролов с фильтром
        // не Ignore. На клики это не влияет — их всё равно перехватывает ScalingViewport
        // внутри MainViewport (у него Stop) и сам пробрасывает в мир.
        MouseFilter = MouseFilterMode.Pass;
        ViewportContainer.MouseFilter = MouseFilterMode.Pass;

        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);

        SetAnchorAndMarginPreset(Resources, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Chat, LayoutPreset.TopRight, margin: 10);
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.CenterRight, margin: 10);
        SetAnchorAndMarginPreset(CommandCard, LayoutPreset.BottomLeft, margin: 10);
        // Именно CenterBottom, а не BottomWide: последний растягивает контрол и якорит его
        // верх по нижней границе экрана, из-за чего панель уезжает за пределы окна.
        SetAnchorAndMarginPreset(Selection, LayoutPreset.CenterBottom, margin: 10);
        SetAnchorAndMarginPreset(Minimap, LayoutPreset.BottomRight, margin: 10);
    }

    /// <summary>
    /// Зум колесом мыши. Колеса нет в перечислении клавиш движка, поэтому забиндить его
    /// через keybinds.yml нельзя — событие приходит только сюда, в UI.
    ///
    /// Событие всплывает от контрола под курсором вверх по дереву, так что до экрана оно
    /// доходит отовсюду, кроме мест, где его уже обработали. Это ровно то, что нужно:
    /// прокрутка над чатом листает чат, а не двигает камеру.
    /// </summary>
    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);

        UserInterfaceManager.GetUIController<RtsHudUIController>().Zoom(args.Delta.Y);
        args.Handle();
    }

    // Мышиный ввод RTS сюда НЕ приходит и прийти не может: MainViewport содержит
    // ScalingViewport с MouseFilter = Stop, он перехватывает хит-тест первым, а _doGuiInput
    // идёт без ignoreStop и обрывается на нём. Зато этот же ScalingViewport сам пробрасывает
    // клик в мир через ViewportKeyEvent — поэтому выделение и приказы живут в
    // RtsSelectionSystem на обычных CommandBinds, как любое другое мировое взаимодействие.
    //
    // Колесо, наоборот, доходит: _doMouseGuiInput вызывается с ignoreStop = true и всплывает
    // сквозь Stop до экрана. Ровно ради этого экрану и нужен MouseFilter = Pass.

    public override ChatBox ChatBox => Chat;

    public override void SetChatSize(Vector2 size)
    {
        SetMarginBottom(Chat, size.X);
        SetMarginLeft(Chat, size.Y);
    }
}
