using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using System;
using System.Text.RegularExpressions;
using Content.Shared.ADT.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Content.Shared.Popups;
using Robust.Client.Player;
using Content.Shared.ADT.btr.Systems;

namespace Content.Client.ADT.btr.UI;

[GenerateTypedNameReferences]
public sealed partial class APCControlWindow : DefaultWindow
{
    [Dependency] private readonly EntityManager _entManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    private SharedPopupSystem _popup;

    public APCControlWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _popup = _entManager.System<SharedPopupSystem>();

        PopupButton1.OnButtonDown += args =>
        {
            if (_playerManager.LocalSession?.AttachedEntity != null)
                _popup.PopupClient("попап1", _playerManager.LocalSession.AttachedEntity);
        };

        PopupButton2.OnButtonDown += args =>
        {
            if (_playerManager.LocalSession?.AttachedEntity != null)
            {
                _popup.PopupClient("попап2", _playerManager.LocalSession.AttachedEntity);
                var _sharedAPCEntitySystem = IoCManager.Resolve<SharedAPCEntitySystem>();
                _sharedAPCEntitySystem.SendLog();
            }
        };
    }
}
