using Content.Client.ADT.RTS.UI.Style;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.RTS.UI.Widgets;

/// <summary>
/// Кнопки событий у правого края: простаивающий рабочий, база под атакой, выход из матча.
/// Кнопка выхода нужна уже сейчас: базовый HUD скрыт, и другого способа выйти мышью нет.
/// См. Docs/ADT/RTS/RTS_MASTER_PLAN.md §5.2.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RtsAlertsPanel : UIWidget
{
    /// <summary>
    /// Игрок нажал «покинуть матч».
    /// </summary>
    public event Action? OnLeavePressed;

    public RtsAlertsPanel()
    {
        RobustXamlLoader.Load(this);

        RtsStyle.ApplyPanel(Background);

        IdleWorkerButton.Text = Loc.GetString("rts-alert-idle-worker-short");
        IdleWorkerButton.ToolTip = Loc.GetString("rts-alert-idle-worker");

        UnderAttackButton.Text = Loc.GetString("rts-alert-under-attack-short");
        UnderAttackButton.ToolTip = Loc.GetString("rts-alert-under-attack");

        LeaveButton.Text = Loc.GetString("rts-alert-leave-short");
        LeaveButton.ToolTip = Loc.GetString("rts-alert-leave");
        LeaveButton.OnPressed += _ => OnLeavePressed?.Invoke();
    }
}
