using System.Numerics;
using Content.Client.ADT.RTS.UI.Style;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.RTS.UI.Widgets;

/// <summary>
/// Сетка команд 6x3 в левом нижнем углу. Содержимое зависит от выделения и
/// наполняется в фазах 6-8; сейчас это пустые слоты нужного размера.
/// См. Docs/ADT/RTS/RTS_MASTER_PLAN.md §5.2.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RtsCommandCard : UIWidget
{
    public const int Columns = 6;
    public const int Rows = 3;

    private readonly List<Button> _slots = new();

    public RtsCommandCard()
    {
        RobustXamlLoader.Load(this);

        RtsStyle.ApplyPanel(Background);

        for (var i = 0; i < Columns * Rows; i++)
        {
            var slot = new Button
            {
                MinSize = new Vector2(48, 48),
                Disabled = true,
                ToggleMode = false,
            };

            _slots.Add(slot);
            Grid.AddChild(slot);
        }
    }

    /// <summary>
    /// Слот сетки. Фаза 6 повесит сюда иконку, стоимость и хоткей.
    /// </summary>
    public Button GetSlot(int index)
    {
        return _slots[index];
    }

    public void ClearSlots()
    {
        foreach (var slot in _slots)
        {
            slot.Text = string.Empty;
            slot.Disabled = true;
        }
    }
}
