using Content.Client.ADT.RTS.UI.Style;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.RTS.UI.Widgets;

/// <summary>
/// Миникарта в правом нижнем углу. Настоящая отрисовка (террейн, туман, точки,
/// прямоугольник вьюпорта) появится в фазе 4 — там же, где считается туман войны.
/// См. Docs/ADT/RTS/RTS_MASTER_PLAN.md §5.2 и §6.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RtsMinimapPanel : UIWidget
{
    public RtsMinimapPanel()
    {
        RobustXamlLoader.Load(this);

        RtsStyle.ApplyPanel(Background);
        RtsStyle.ApplyBar(MapBox);

        Placeholder.Text = Loc.GetString("rts-minimap-placeholder");
    }
}
