using Content.Client.ADT.RTS.UI.Style;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.RTS.UI.Widgets;

/// <summary>
/// Панель ресурсов в левом верхнем углу: дерево, пшеница, руда и население.
/// Данные подключаются в фазах 5 и 6, сейчас панель показывает нули.
/// См. Docs/ADT/RTS/RTS_MASTER_PLAN.md §5.2.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RtsResourcePanel : UIWidget
{
    public RtsResourcePanel()
    {
        RobustXamlLoader.Load(this);

        RtsStyle.ApplyIcon(WoodIcon, RtsStyle.WoodColor);
        RtsStyle.ApplyIcon(WheatIcon, RtsStyle.WheatColor);
        RtsStyle.ApplyIcon(OreIcon, RtsStyle.OreColor);
        RtsStyle.ApplyIcon(PopIcon, RtsStyle.PopColor);

        RtsStyle.ApplyBar(WoodBar);
        RtsStyle.ApplyBar(WheatBar);
        RtsStyle.ApplyBar(OreBar);
        RtsStyle.ApplyBar(PopBar, RtsStyle.PopColor);

        RtsStyle.ApplyBar(WoodCountBox);
        RtsStyle.ApplyBar(WheatCountBox);
        RtsStyle.ApplyBar(OreCountBox);
        RtsStyle.ApplyBar(PopCountBox, RtsStyle.PopColor);
    }

    /// <summary>
    /// Обновляет одну строку ресурса. Счётчик — число рабочих на ресурсе.
    /// </summary>
    public void SetResource(int wood, int wheat, int ore, int cap)
    {
        WoodValue.Text = $"{wood}/{cap}";
        WheatValue.Text = $"{wheat}/{cap}";
        OreValue.Text = $"{ore}/{cap}";
    }

    public void SetWorkers(int wood, int wheat, int ore)
    {
        WoodCount.Text = wood.ToString();
        WheatCount.Text = wheat.ToString();
        OreCount.Text = ore.ToString();
    }

    public void SetPopulation(int population, int cap, int idleWorkers)
    {
        PopValue.Text = $"{population}/{cap}";
        PopCount.Text = idleWorkers.ToString();
    }
}
