using Content.Client.ADT.RTS.UI.Style;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.RTS.UI.Widgets;

/// <summary>
/// Панель выделения по центру снизу: портрет, здоровье, статы и очередь производства.
/// Наполняется в фазе 3 (юниты) и фазе 8 (очереди найма).
/// См. Docs/ADT/RTS/RTS_MASTER_PLAN.md §5.2.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RtsSelectionPanel : UIWidget
{
    public RtsSelectionPanel()
    {
        RobustXamlLoader.Load(this);

        RtsStyle.ApplyPanel(Background);
        RtsStyle.ApplyBar(PortraitBox);
        RtsStyle.ApplyBar(HealthBox);
        RtsStyle.ApplyBar(StatsBox);
        RtsStyle.ApplyBar(QueueBox);

        Clear();
    }

    /// <summary>
    /// Ничего не выделено: панель прячется целиком, как в классических RTS.
    /// </summary>
    public void Clear()
    {
        Visible = false;
        UnitName.Text = string.Empty;
        HealthValue.Text = string.Empty;
        AttackValue.Text = string.Empty;
        ArmorValue.Text = string.Empty;
        RangeValue.Text = string.Empty;
        SpeedValue.Text = string.Empty;
        QueueTitle.Text = string.Empty;
    }

    public void ShowUnit(string name, int health, int maxHealth)
    {
        Visible = true;
        UnitName.Text = name;
        HealthValue.Text = $"{health}/{maxHealth}";
    }

    public void SetStats(int attack, int armor, int range, float speed)
    {
        AttackValue.Text = Loc.GetString("rts-stat-attack", ("value", attack));
        ArmorValue.Text = Loc.GetString("rts-stat-armor", ("value", armor));
        RangeValue.Text = Loc.GetString("rts-stat-range", ("value", range));
        SpeedValue.Text = Loc.GetString("rts-stat-speed", ("value", speed));
    }
}
